config/routes.rb
Visitorr::Application.routes.draw do

  # get "plans/index"
  

  # get "profiles/show"
  # 
  # get "profiles/edit"

  resources :profiles
  resources :sessions
  resources :users do
    resource :visitor
  end
  
  resources :visitors do
    resource :profile
  end
  resources :visitors
  resources :contacts
  resources :password_resets
  
  match "signin", :to => "sessions#new", :as =>:sign_in
  match "settings" => "users#edit", :as => :settings 
  match "get-started", :to => "users#new", :as => :get_started
  match "signout", :to => "sessions#destroy", :as => :sign_out
  match "success", :to => "visitors#success", :as => :success
  match "cancel_subscription", :to => "users#cancel_subscription", :as => "cancel_subscription"
  match "admin", :to => "admin#visitors", :as => :admin
  match "test-email", :to => "profiles#test_email", :as => "test_email"
  match "reset-password", :to => "sessions#reset_password", :as => "reset_password"
  match "plans", :to => "plans#index", :as => :plans
  match "update-plans", :to => "plans#update", :as => :update_plans
  get 'how-it-works', :to => "pages#hiw", :as => :hiw
  get 'contact-us', :to => "contacts#new", :as => :contact_us
  
  get 'paypal/checkout', :to => "users#paypal_checkout"
  get 'paypal/update',   :to => "users#paypal_update"
  
  root :to => "pages#home"

  match ':id', :to => "visitors#new"
  
  match ":profile", :to => "profiles#create"

  match "/admin/export", :to => "admin#export_emails", :as => "export"

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  has_many :visitors
  attr_accessible :address, :phone, :video_url, :subject, :body, :question_one, :question_two,
                  :question_three, :question_four, :question_five
  
  validates_presence_of :subject, :body

end


# == Schema Information
#
# Table name: profiles
#
#  id             :integer         not null, primary key
#  address        :string(255)
#  phone          :string(255)
#  video_url      :string(255)
#  subject        :string(255)
#  body           :text
#  user_id        :integer
#  created_at     :datetime
#  updated_at     :datetime
#  question_one   :string(255)
#  question_two   :string(255)
#  question_three :string(255)
#  question_four  :string(255)
#  question_five  :string(255)
#

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_filter :require_login
  before_filter :subscribed
  
  def show
    @user = User.find_by_id(current_user.id)
    @profile = Profile.find_by_user_id(@user.id)
    @visitor = Visitor.find_by_user_id(@user.id)
    if @profile.nil?
      redirect_to new_profile_path
    end
    #if @visitor.nil?
    #  redirect_to new_visitors_profiles
    #end
  end
  
  def new
    @user = current_user
    @profile = @user.build_profile
  end
  
  def create
    @user = User.find_by_id(current_user.id)
    @profile = @user.build_profile(params[:profile])
    @visitor = Visitor.find_by_user_id(@user.id)
    if @visitor.save
      redirect_to visitor_path(@visitor), :notice => "Profile updated"
    else
      render 'new'
    end
    #if @profile.save
    #  redirect_to visitor_profile_path(@user), :notice => "Profile updated"
    #else
    #  render 'new'
    #end
  end
  
  def edit
    @user = current_user
    @profile = Profile.find_by_user_id(@user.id) || @user.build_profile
  end
  
  def update
    @user = current_user
    @profile = Profile.find_by_user_id(@user.id) || @user.build_profile
    if @profile.update_attributes(params[:profile])
      redirect_to profile_path(@user), :notice => "Profile updated"
    else
      render 'edit'
    end
  end
  
  def test_email
    @user = current_user
    @profile = Profile.find_by_user_id(@user.id)
    if @profile
      TestMailer.test(@user).deliver
      redirect_to profile_path(@user), :notice => "Test email has been sent"
    else
      flash.now.notice = "You need to save your profile first."
      render new_profile_path
    end
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/edit.html.haml
.row
  .span10.columns
    %fieldset
      = form_for @profile, :html => {:class => 'form-stacked'} do |f|
        - if @profile.errors.any?
          .alert-message.block-message.error
            %p #{pluralize(@profile.errors.count, "problem")} with your registration:
            .errors
              - @profile.errors.full_messages.each do |msg|
                %p= msg



        .clearfix
          = f.label "Organization's Physical Address"
          .input
            = f.text_field :address, :class => "field"
        .clearfix
          = f.label "Organizations Phone Number"
          .input
            = f.text_field :phone, :class => "field"
        .clearfix
          = f.label :subject, "Email subject"
          .input
            = f.text_field :subject, :class => "field"
        %span.help-block
          The Subject line your visitors will see in their inbox.
        .clearfix
          = f.label :body, "Email body"
          .input
            = javascript_include_tag "/javascripts/ckeditor/ckeditor.js"
            = javascript_include_tag "editor.js"
            = f.text_area :body, :class => "email_body"
        %span.help-block
          Information you would like your visitors to be aware of. Upcoming Events, Church information, Vision or Mission Statement, etc.
        .clearfix
          = f.label :video_url, "Video URL"
          .input
            = f.text_field :video_url, :class => "field"
        %span.note Upload your video to 
        = link_to "YouTube", "http://youtube.com/my_webcam"
        then click 
        %br/ 
        "view on video page" and copy the url
        %br/
        in the address bar and paste it here.

        %hr/
        %span.note Enter some questions you would like your visitors to answer
        .clearfix
          = f.label "Question 1."
          .input
            = f.text_field :question_one, :class => "field"
        .clearfix
          = f.label "Question 2"
          .input
            = f.text_field :question_two, :class => "field"
        .clearfix
          = f.label "Question 3"
          .input
            = f.text_field :question_three, :class => "field"
        .clearfix
          = f.label "Question 4"
          .input
            = f.text_field :question_four, :class => "field"
        .clearfix
          = f.label "Question 5"
          .input
            = f.text_field :question_five, :class => "field"   

        .actions
          = f.submit("Update", :class => "btn primary")

app/views/profiles/new.html.haml
.row
  .span10.columns
    %fieldset
      = form_for @profile, :html => {:class => 'form-stacked'} do |f|
        - if @profile.errors.any?
          .alert-message.block-message.error
            %p #{pluralize(@profile.errors.count, "problem")} with your registration:
            .errors
              - @profile.errors.full_messages.each do |msg|
                %p= msg



        .clearfix
          = f.label "Organization's Physical Address"
          .input
            = f.text_field :address, :class => "field"
        .clearfix
          = f.label "Organizations Phone Number"
          .input
            = f.text_field :phone, :class => "field"
        .clearfix
          = f.label :subject, "Email subject"
          .input
            = f.text_field :subject, :class => "field"
        %span.help-block
          The Subject line your visitors will see in their inbox on Monday morning.
        .clearfix
          = f.label :body, "Email body"
          .input
            = javascript_include_tag "/javascripts/ckeditor/ckeditor.js"
            = javascript_include_tag "editor.js"
            = f.text_area :body, :class => "email_body"
        %span.help-block
          Information you would like your visitors to be aware of. Upcoming Events, Church information, Vision or Mission Statement, etc.
        .clearfix
          = f.label :video_url, "Video URL"
          .input
            = f.text_field :video_url, :class => "field"
        %span.note Upload your video to 
        = link_to "YouTube", "http://youtube.com/my_webcam"
        then click 
        %br/ 
        "view on video page" and copy the url
        %br/
        in the address bar and paste it here.

        %hr/
        %span.note Enter some questions you would like your visitors to answer
        .clearfix
          = f.label "Question 1."
          .input
            = f.text_field :question_one, :class => "field"
        .clearfix
          = f.label "Question 2"
          .input
            = f.text_field :question_two, :class => "field"
        .clearfix
          = f.label "Question 3"
          .input
            = f.text_field :question_three, :class => "field"
        .clearfix
          = f.label "Question 4"
          .input
            = f.text_field :question_four, :class => "field"
        .clearfix
          = f.label "Question 5"
          .input
            = f.text_field :question_five, :class => "field"                                                

        .actions
          = f.submit("Update", :class => "btn primary")

app/views/profiles/show.html.erb
<p>
  <h5 id="address">Organization's Physical Address:</h5> <%= @profile.address %>
</p>
<p>
  <h5 id="phone">Organization's Phone Number:</h5> <%= @profile.phone %>
</p>
<p>
  <h5 id="video url">Video url:</h5> <%= link_to @profile.video_url, @profile.video_url %>
</p>
<p>
  <h5 id="subject:">Email Subject</h5> <%= @profile.subject %>
</p>
<p>
  <h5 id="body:">Email Body:</h5>
</p>
<p class="email_body"><%= @profile.body.html_safe %></p>

<p>
  <h5 class="questions">Question 1: </h5><h5><%= @profile.question_one %></h5>
</p>
<p>
  <h5 class="questions">Question 2:</h5><h5><%= @profile.question_two %></h5>
</p>
<p>
  <h5 class="questions">Question 3:</h5><h5><%= @profile.question_three %></h5>
</p>
<p>
  <h5 class="questions">Question 4:</h5><h5><%= @profile.question_four %></h5>
</p>
<p>
  <h5 class="questions">Question 5:</h5><h5><%= @profile.question_five %></h5>
</p>

<%= button_to "Send Test", test_email_path, :class => "btn primary" %> 
<%= button_to "Edit profile", edit_profile_path, :class => "btn primary", :method => :get %>