config/routes.rb
Visitorr::Application.routes.draw do

  # get "plans/index"
  

  # get "profiles/show"
  # 
  # get "profiles/edit"

  resources :profiles
  resources :sessions
  resources :users do
    resource :visitor
  end
  
  resources :visitors do
    resource :profile
  end
  resources :visitors
  resources :contacts
  resources :password_resets
  
  match "signin", :to => "sessions#new", :as =>:sign_in
  match "settings" => "users#edit", :as => :settings 
  match "get-started", :to => "users#new", :as => :get_started
  match "signout", :to => "sessions#destroy", :as => :sign_out
  match "success", :to => "visitors#success", :as => :success
  match "cancel_subscription", :to => "users#cancel_subscription", :as => "cancel_subscription"
  match "admin", :to => "admin#visitors", :as => :admin
  match "test-email", :to => "profiles#test_email", :as => "test_email"
  match "reset-password", :to => "sessions#reset_password", :as => "reset_password"
  match "plans", :to => "plans#index", :as => :plans
  match "update-plans", :to => "plans#update", :as => :update_plans
  get 'how-it-works', :to => "pages#hiw", :as => :hiw
  get 'contact-us', :to => "contacts#new", :as => :contact_us
  
  get 'paypal/checkout', :to => "users#paypal_checkout"
  get 'paypal/update',   :to => "users#paypal_update"
  
  root :to => "pages#home"

  match ':id', :to => "visitors#new"
  
  match ":profile", :to => "profiles#create"

  match "/admin/export", :to => "admin#export_emails", :as => "export"

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  has_unique_slug :column => :slug, :subject => :name

  before_save :make_slug
  has_many :visitors, :dependent => :destroy
  has_one :profile, :dependent => :destroy
  accepts_nested_attributes_for :profile
  belongs_to :plan
    
  attr_accessor :stripe_card_token, :paypal_payment_token

  attr_accessible :email, :password, :password_confirmation, :name, :stripe_token, :last_4_digits, 
  :subscribed, :stripe_customer_token, :stripe_card_token, :paypal_customer_token, :paypal_payment_token, 
  :paypal_recurring_profile_token, :plan_id
  attr_accessible :email, :password, :password_confirmation, :name, :stripe_token, :last_4_digits, :subscribed, :stripe_customer_token, :stripe_card_token, :paypal_customer_token, :paypal_payment_token, :paypal_recurring_profile_token, :plan_id

  validates_confirmation_of   :password
  validates_presence_of       :password, :on => :create
  validates_uniqueness_of     :name, :slug
  validates_format_of         :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i

  validates :email, :uniqueness => { :case_sensitive => false },
                    :presence => true

  validates :name,  :uniqueness => { :case_sensitive => false },
                    :presence => true

  validates :slug,  :uniqueness => { :case_sensitive => false }
  
  def save_with_payment
    if valid?
      if paypal_payment_token.present?
        save_with_paypal_payment
      else
        save_with_stripe_payment
      end
    end
  end
  
  def save_with_paypal_payment
    response = paypal.make_recurring
    self.paypal_recurring_profile_token = response.profile_id
    self.subscribed = true
    save!
  end
  
  def update_with_paypal(token, payerid)
    self.paypal_payment_token = token
    self.paypal_customer_token = payerid
    response = paypal.make_recurring
    self.paypal_recurring_profile_token = response.profile_id
    self.subscribed = true
    save!
  end
  
  def paypal
    PaypalPayment.new(self)
  end
  
  def save_with_stripe_payment
      customer = Stripe::Customer.create(:description => email, :plan => plan_id, :card => stripe_card_token)
      self.stripe_customer_token = customer.id
      self.subscribed = true
      self.last_4_digits = customer.active_card.last4
      save!
  rescue Stripe::InvalidRequestError => e
    logger.error "Stripe error while creating customer: #{e.message}"
    errors.add :base, "There was a problem with your credit card."
    false
  end
  
  def update_with_stripe
    customer = Stripe::Customer.retrieve(stripe_customer_token)
    customer.card = stripe_token
    customer.save
    self.subscribed = true
    self.last_4_digits = customer.active_card.last4
    save!
  rescue Stripe::InvalidRequestError => e
    logger.error "Stripe error while creating customer: #{e.message}"
    errors.add :base, "There was a problem with your credit card."
  false
  end

  def make_slug
    self.slug = self.name.parameterize
  end
  
  def payment_provided?
    stripe_card_token.present? || paypal_payment_token.present? 
  end
  
  
  # before_save :update_stripe  
  # attr_accessor :stripe_token
  
  # 
  # def update_stripe
  #   if stripe_token.present?
  #     if stripe_id.nil?
  #       customer = Stripe::Customer.create(
  #         :description => email,
  #         :card => stripe_token
  #       )
  #       self.last_4_digits = customer.active_card.last4
  #       response = customer.update_subscription({:plan => "Visitorr+"})
  #     else
  #       customer = Stripe::Customer.retrieve(stripe_id)
  #       customer.card = stripe_token
  #       customer.save
  #       self.last_4_digits = customer.active_card.last4
  #     end
  # 
  #     self.stripe_id = customer.id
  #     self.stripe_token = nil
  #     self.subscribed = true
  #   elsif last_4_digits_changed?
  #     self.last_4_digits = last_4_digits_was
  #   end
  #   rescue Stripe::InvalidRequestError => e  
  # logger.error "Stripe error while creating customer: #{e.message}"  
  # errors.add :base, "There was a problem with your credit card." 
  # end
  
end

# == Schema Information
#
# Table name: users
#
#  id                              :integer         not null, primary key
#  email                           :string(255)     not null
#  crypted_password                :string(255)
#  salt                            :string(255)
#  created_at                      :datetime
#  updated_at                      :datetime
#  remember_me_token               :string(255)
#  remember_me_token_expires_at    :datetime
#  slug                            :string(255)
#  name                            :string(255)
#  address                         :string(255)
#  phone                           :string(255)
#  video                           :string(255)
#  last_4_digits                   :string(255)
#  stripe_id                       :string(255)
#  subscribed                      :boolean         default(FALSE)
#  subject                         :string(255)
#  email_body                      :text
#  stripe_customer_token           :string(255)
#  paypal_customer_token           :string(255)
#  paypal_recurring_profile_token  :string(255)
#  reset_password_token            :string(255)
#  reset_password_token_expires_at :datetime
#  reset_password_email_sent_at    :datetime
#  plan_id                         :integer
#

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_login, :only => [:edit, :update]

  def new
    if params[:plan_id]
      plan = Plan.find(params[:plan_id])
      @user = plan.users.build
    else
      redirect_to plans_path
    end
    if params[:PayerID]
      @user.paypal_customer_token = params[:PayerID]
      @user.paypal_payment_token = params[:token]
      @user.email = @user.paypal.checkout_details.email
    end
  end

  def create
    @user = User.new(params[:user])
    if @user.save_with_payment
      login(params[:user][:email], params[:user][:password])
      redirect_to profile_path(@user), :notice => "Welcome to Visitorr! Please take a moment to fill in your information. This information will be sent to your visitors!"
    else
      render :new
    end
  end
  
  def edit
    @user = current_user
    if @user.subscribed == false
      if params[:plan_id]
        @user.plan_id = params[:plan_id]
      else
        redirect_to update_plans_path
      end
    end
    if params[:PayerID]
      @user = current_user
      @user.update_with_paypal(params[:token], params[:PayerID])
      redirect_to settings_url, :notice => "Your subscription has been updated! We knew you'd be back."
    end
  end
  
  def update
    @user = current_user      
    if @user.update_attributes(params[:user])
      redirect_to settings_path, :notice => "Profile Updated!"
    else 
      redirect_to settings_path, :notice => "I'm sorry, that didn't save. Please try again."
    end
  end

  def cancel_subscription
    if @user = current_user
      if @user.paypal_recurring_profile_token.present?
        @user.paypal.cancel_recurring
        @user.update_attributes(:subscribed => false, :paypal_recurring_profile_token => nil)
        redirect_to settings_path, :notice => "Your subscription has been cancelled."
      else
        cu = Stripe::Customer.retrieve(@user.stripe_customer_token)
        if cu.cancel_subscription
          @user.update_attributes(:subscribed => false, :last_4_digits => "")
          redirect_to settings_path, :notice => "You'll be back.. they always come back"
        end
      end
    end
  end
  
  def failed_payment
    @user = User.find_by_stripe_id(params[:invoice][:customer])
    @event = params[:invoice][:event]
    if @event == "recurring_payment_failed"
      @user.update_attributes(:subscribed => false, :last_4_digits => nil)
    end
  end
  
  def paypal_checkout
    plan = Plan.find(params[:plan_id])
    @user = current_user || plan.users.build 
    if current_user
      redirect_to @user.paypal.checkout_url(
      return_url: settings_url(:plan_id => plan.id),
      cancel_url: settings_url)
    else
      redirect_to @user.paypal.checkout_url(
      return_url: new_user_url(:plan_id => plan.id),
      cancel_url: root_url)
    end
  end  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_payment_options.html.haml
.field
  = radio_button_tag :pay_with, :card, true
  = label_tag :pay_with_card do
    = image_tag "visa.png"
    = image_tag "mastercard.png"
    = image_tag "discover.png"
    = image_tag "american_express.png"
  = radio_button_tag :pay_with, :paypal
  = label_tag :pay_with_paypal do
    = image_tag "paypal.png"
    %br/
    %br/
    
#paypal_checkout{:style => "display:none"}
  = link_to image_tag("https://www.paypal.com/en_US/i/btn/btn_xpressCheckout.gif"), paypal_checkout_path

app/views/users/_rc_form.html.haml
.row
  .span6.columns
    %fieldset
      = form_for user, :html => {:class => 'form-stacked'} do |f|
        - if user.errors.any?
          .alert-message.block-message.error
            %p #{pluralize(user.errors.count, "problem")} with your registration:
            .errors
              - user.errors.full_messages.each do |msg|
                %p= msg

        - unless user.payment_provided? || user.subscribed === true   
          .field
            = radio_button_tag :pay_with, :card, true
            = label_tag :pay_with_card do
              = image_tag "visa.png"
              = image_tag "mastercard.png"
              = image_tag "discover.png"
              = image_tag "american_express.png"
              = image_tag "jcb.png"
            = radio_button_tag :pay_with, :paypal
            = label_tag :pay_with_paypal do
              = image_tag "paypal.png"
            %br/
            %br/
        #paypal_checkout{:style => "display:none"}
          = link_to image_tag("https://www.paypal.com/en_US/i/btn/btn_xpressCheckout.gif"), paypal_checkout_path(plan_id: @user.plan_id)

        #billing_fields
          .clearfix
            = f.label :name, "Organization name"
            .input
              = f.text_field :name, :class => "field"
              - if defined? editing
                %span.help-block  
                  This is your url - visitors can find you at:
                  = link_to "#{request.env["HTTP_HOST"]}/#{user.slug}", root_url() + "#{user.slug}"
              - else
                %span.help-block 
                  Organization name will appear as URL ex. www.visitorr.com/YOURnameHERE  keep it short

          .clearfix
            = f.label :email
            .input
              = f.text_field :email, :class => "field"

          .clearfix
            = f.label :password
            .input
              = f.password_field :password, :class => "field"
              - if defined? editing
                %span.help-block Leave blank to keep your current password

          .clearfix
            = f.label :password_confirmation
            .input
              = f.password_field :password_confirmation, :class => "field"

            = f.hidden_field :stripe_card_token
            = f.hidden_field :last_4_digits
            = f.hidden_field :paypal_customer_token
            = f.hidden_field :paypal_payment_token
            = f.hidden_field :plan_id

        
          - if user.subscribed == true
            #cancel-subscription.clearfix
              = link_to "Cancel subscription", cancel_subscription_path

        
        
          %noscript
            %p
              This form requires Javascript to use

          - if user.payment_provided?
            %span.note
              Payment has been provided. Click subscribe to complete your registration.
          - else
            - unless user.payment_provided? || user.subscribed === true   
              #credit-card
                #credit-card-errors{:style => "display:none"}
                  #stripe-error-message.alert-message.block-message.error

                / these fields are disabled before submission and are never transmitted back to rails
                .clearfix
                  = label_tag :card_number, "Credit Card Number"
                  .input
                    = text_field_tag :card_number, nil, name: nil

                .clearfix
                  = label_tag :card_code, "Security Code on Card (CVV)"
                  .input
                    = text_field_tag :card_code, nil, name: nil

                .clearfix
                  = label_tag :card_month, "Card Expiration"
                  .input
                    = select_month nil, {add_month_numbers: true}, {name: nil, id: "card_month", :class => "medium"}
                    = select_year nil, {start_year: Date.today.year, end_year: Date.today.year+15}, {name: nil, id: "card_year", :class => "small"}

                  /empty
                %span.note
                  Your credit card details will be sent directly to our payment processor
        .actions
          = f.submit((defined?(editing) ? "Update" : "Subscribe"), :class => "btn primary")

app/views/users/edit.html.haml
.page-header
  %h1 Account Settings
= javascript_include_tag "https://js.stripe.com/v1/"
= render :partial => 'users/rc_form', :locals => {:user => current_user, :editing => true}

app/views/users/new.html.erb
<div class="page-header">
  <h1>Register - <%= number_to_currency @user.plan.price %>/month - Free 30 Day Trial!</h1>
  <%= javascript_include_tag "https://js.stripe.com/v1/" %>
  <%= render :partial => "users/rc_form", :locals => {:user => @user } %>
</div>