config/routes.rb
Visitorr::Application.routes.draw do

  # get "plans/index"
  

  # get "profiles/show"
  # 
  # get "profiles/edit"

  resources :profiles
  resources :sessions
  resources :users do
    resource :visitor
  end
  
  resources :visitors do
    resource :profile
  end
  resources :visitors
  resources :contacts
  resources :password_resets
  
  match "signin", :to => "sessions#new", :as =>:sign_in
  match "settings" => "users#edit", :as => :settings 
  match "get-started", :to => "users#new", :as => :get_started
  match "signout", :to => "sessions#destroy", :as => :sign_out
  match "success", :to => "visitors#success", :as => :success
  match "cancel_subscription", :to => "users#cancel_subscription", :as => "cancel_subscription"
  match "admin", :to => "admin#visitors", :as => :admin
  match "test-email", :to => "profiles#test_email", :as => "test_email"
  match "reset-password", :to => "sessions#reset_password", :as => "reset_password"
  match "plans", :to => "plans#index", :as => :plans
  match "update-plans", :to => "plans#update", :as => :update_plans
  get 'how-it-works', :to => "pages#hiw", :as => :hiw
  get 'contact-us', :to => "contacts#new", :as => :contact_us
  
  get 'paypal/checkout', :to => "users#paypal_checkout"
  get 'paypal/update',   :to => "users#paypal_update"
  
  root :to => "pages#home"

  match ':id', :to => "visitors#new"
  
  match ":profile", :to => "profiles#create"

  match "/admin/export", :to => "admin#export_emails", :as => "export"

end

app/views/layouts/_footer.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-3113013-19']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= "Visitorr"
    = stylesheet_link_tag :application
    = tag :meta, :name => "stripe-key", :content => "pk_1bBAOyEcLIiPQzHQv6Qck5SueApPy"
    = javascript_include_tag :application
    = csrf_meta_tag

  %body{ :id => "#{params[:controller].parameterize}_controller"  }
    .topbar
      .navcontainer
        %h3= link_to image_tag('logo1.png'), root_path
        %ul.nav
          - if current_user
            %li= link_to "Visitors", admin_path
            %li= link_to "Profile", profile_path(current_user)
            %li= link_to "Settings", settings_path
            %li= link_to "Sign Out", sign_out_path
          - else
            %li= link_to "Get Started", get_started_path
            %li= link_to "How It Works", hiw_path
            %li= link_to "Contact Us", contact_us_path
            %li= link_to "Sign In", sign_in_path

    #header
    .container
      .main
        .row
          .span6.columns
            - if flash.notice
              #notice.alert-message.block-message.success= flash.notice
        = yield
        = debug(params) if Rails.env.development?

    = render "layouts/footer"

app/views/layouts/application.mobile.haml
!!!
%html
  %head
    %title= "Visitorr"
    = stylesheet_link_tag :application
    = javascript_include_tag "https://js.stripe.com/v1/"
    = javascript_tag "Stripe.publishableKey = '#{STRIPE_PUBLIC_KEY}';";
    = javascript_include_tag :application
    = csrf_meta_tag
    %meta{:name => "apple-mobile-web-app-capable", :content => "yes"}
    %meta{:name => "viewport", :content => "user-scalable=false, width=device-width"}

  %body{ :id => "#{params[:controller].parameterize}_mobile"  }
    .mobile.navcontainer      
      .mobile.topbar
        %h3= link_to image_tag('logo.png'), root_path

    #header
    .mobile.container
      .mobile.main
        .row
          .spanmob.columns
            - if flash.notice
              #notice.alert-message.block-message.success= flash.notice
        .org_name
          - if @user
            %h3= "#{@user.name}"              
        = yield
        = debug(params) if Rails.env.development?
        
  = render "visitors/footer"

app/views/layouts/landing_page.html.haml
!!!
%html
  %head
    %title= "Visitorr"
    = stylesheet_link_tag :application
    = javascript_include_tag "https://js.stripe.com/v1/"
    = javascript_tag "Stripe.publishableKey = '#{STRIPE_PUBLIC_KEY}';";
    = javascript_include_tag :application
    = csrf_meta_tag

  %body{ :id => "#{params[:controller].parameterize}"  }
    .topbar
      .navcontainer
        %h3= link_to image_tag('logo1.png'), root_path
        %ul.nav
          - if current_user
            %li= link_to "Visitors", admin_path
            %li= link_to "Profile", profile_path(current_user)
            %li= link_to "Settings", settings_path
            %li= link_to "Sign Out", sign_out_path
          - else
            %li= link_to "Get Started", get_started_path
            %li= link_to "How It Works", hiw_path
            %li= link_to "Contact Us", contact_us_path
            %li= link_to "Sign In", sign_in_path

    #header
      .headercontainer
        #headtext
          %h2 
          %h4 
          %p  
          %p= link_to image_tag("iphone4.png"), get_started_path, :class => "getstarted"
        #headimg
          %span
            %iframe{:allowFullScreen => "", :frameborder => "0", :height => "281", :mozallowfullscreen => "", :src => "http://player.vimeo.com/video/33996675?title=0&byline=0&portrait=0", :webkitAllowFullScreen => "", :width => "430"}
        #headimg
    .container
      .main
        .row
          .span6.columns
            - if flash.notice
              #notice.alert-message.block-message.success= flash.notice
        = yield
        
        #imagecontainer
          .imagebox
            = image_tag("assimilation.png")
          .imagebox
            = image_tag("connect.png")
          .imagebox
            = image_tag("growth.png")   
            

  = render "layouts/footer"
                        